import type { CSSProperties } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import {
  FaArrowRight,
  FaBoxOpen,
  FaCertificate,
  FaCheckCircle,
  FaGlobeAsia,
  FaHandHoldingWater,
  FaIndustry,
  FaLeaf,
  FaRecycle,
  FaSeedling,
  FaShippingFast,
  FaSolarPanel,
  FaUsers,
  FaWater,
} from "react-icons/fa";

import SectionTitle from "@/components/SectionTitle";
import PremiumPageBanner from "@/components/PremiumPageBanner";
import { siteConfig } from "@/data/site";

export const metadata: Metadata = {
  title: "Sustainability",
  description: `See how ${siteConfig.name} approaches renewable energy, water recovery, waste reduction, responsible packaging and ethical manufacturing.`,
};

const metrics = [
  {
    value: "50%",
    progress: 50,
    label: "Renewable electricity",
    description: "of total electricity usage is generated by on-site rooftop solar panels.",
    color: "#FBAA00",
  },
  {
    value: "−15%",
    progress: 15,
    label: "Carbon emissions",
    description: "year-over-year reduction in Scope 1 & 2 CO₂ emissions per unit produced.",
    color: "#FBAA00",
  },
  {
    value: "85%",
    progress: 85,
    label: "Certified eco materials",
    description: "supported by FSC-certified cartons and sustainable poly bags.",
    color: "#579515",
  },
  {
    value: "100%",
    progress: 100,
    label: "Audited facilities",
    description: "facilities maintaining amfori BSCI social-compliance auditing.",
    color: "#579515",
  },
];

const pillars = [
  {
    Icon: FaSolarPanel,
    number: "01",
    title: "Solar energy",
    image: "/images/sustainability/solar.jpeg",
    summary:
      "Rooftop solar generation helps reduce dependence on conventional grid electricity across our operations.",
    points: ["50% renewable electricity", "On-site rooftop generation", "Lower operational emissions"],
  },
  {
    Icon: FaWater,
    number: "02",
    title: "Water management",
    image: "/images/sustainability/water.jpeg",
    summary:
      "Engineering-led process controls minimise freshwater withdrawal and maximise recovery for reuse.",
    points: ["Low-liquor ratio dyeing & printing", "90% process-water recycling", "Reverse-osmosis recovery"],
  },
  {
    Icon: FaRecycle,
    number: "03",
    title: "Waste & recycling",
    image: "/images/sustainability/recycling.jpeg",
    summary:
      "Production by-products are separated at source and redirected towards useful second-life applications.",
    points: ["100% source segregation", "Fabric-scrap upcycling", "Zero waste to landfill goal"],
  },
  {
    Icon: FaBoxOpen,
    number: "04",
    title: "Eco-conscious packaging",
    image: "/images/sustainability/packaging.jpeg",
    summary:
      "Packaging is designed to reduce single-use plastic and material waste while protecting every shipment.",
    points: ["FSC-certified cartons", "Sustainable poly bags", "Freight optimisation"],
  },
  {
    Icon: FaUsers,
    number: "05",
    title: "Ethical manufacturing",
    image: "/images/sustainability/solar.jpeg",
    summary:
      "Responsible workplace practices support the people behind every product and strengthen accountability across our operation.",
    points: ["Audited facilities", "Fair workplace practices", "Responsible sourcing"],
  },
];

const waterFlow = [
  { Icon: FaHandHoldingWater, label: "Lower intake", detail: "Freshwater demand minimised" },
  { Icon: FaIndustry, label: "Efficient process", detail: "Low-liquor production" },
  { Icon: FaRecycle, label: "90% recycled", detail: "Process water recovered" },
  { Icon: FaWater, label: "RO recovery", detail: "Water prepared for reuse" },
];

const circularSteps = [
  { Icon: FaSeedling, label: "Responsible inputs" },
  { Icon: FaIndustry, label: "Efficient production" },
  { Icon: FaRecycle, label: "Source segregation" },
  { Icon: FaLeaf, label: "Scrap upcycling" },
  { Icon: FaBoxOpen, label: "Smarter packaging" },
  { Icon: FaShippingFast, label: "Optimised freight" },
];

export default function SustainabilityPage() {
  return (
    <main className="sustainability-page overflow-hidden bg-white">
      <PremiumPageBanner eyebrow="Responsibility in every thread" title={<>Textiles made with <span className="text-[#FBAA00]">tomorrow in mind.</span></>} description="From solar-powered operations and water recovery to responsible materials and ethical labour, we are working towards a lighter footprint." current="Sustainability" bgImage="/images/sustainability/solar.jpeg" />
      <section className="hidden">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/images/contact/contact-textile-banner-v3.png" alt="Floating woven textile ribbons" className="premium-banner-image absolute inset-0 h-full w-full object-cover" />
        <div className="absolute inset-0 bg-[#579515]/80" />
        <div className="absolute inset-y-0 left-0 w-2 bg-[#FBAA00]" />

        <div className="container-x relative flex h-[125px] flex-col justify-end pb-2.5 pt-8 lg:h-[145px] lg:pb-3">
          <div className="mb-1 flex items-center gap-2 text-[9px] font-bold uppercase tracking-[0.18em] text-[#FEFEFE]">
            <Link href="/" className="text-[#FBAA00] transition-colors hover:text-[#FEFEFE]">Home</Link>
            <span className="text-[#FEFEFE]/60">/</span>
            <span>Sustainability</span>
          </div>
          <div className="mb-0.5 flex items-center gap-2 text-[8px] font-bold uppercase tracking-[0.24em] text-[#FBAA00]">
            <span className="h-0.5 w-8 bg-[#FBAA00]" /> Responsibility in every thread
          </div>
          <h1 className="max-w-4xl font-sans text-3xl font-semibold uppercase leading-[1.1] tracking-tight text-[#FEFEFE] [text-shadow:0_3px_8px_rgba(0,0,0,0.85)] sm:text-4xl">Textiles made with tomorrow in mind.</h1>
          <p className="mt-0.5 max-w-2xl text-[9px] font-bold leading-3.5 text-[#FEFEFE]/90 sm:text-[10px]">From solar-powered operations and water recovery to responsible materials and ethical labour, we are working towards a lighter footprint.</p>
        </div>
      </section>

      {/* Impact dashboard */}
      <section className="section-y relative z-10">
        <div className="container-x">
          <div className="grid gap-4 [perspective:1200px] sm:grid-cols-2 lg:grid-cols-4">
            {metrics.map((metric, index) => (
              <article
                key={metric.label}
                className={`group relative min-h-[180px] overflow-hidden rounded-[1.25rem] border border-[#ECECEC] bg-[#FEFEFE]/80 p-5 shadow-[6px_8px_0_rgba(87,149,21,0.08),0_18px_32px_-24px_rgba(87,149,21,0.45)] backdrop-blur-xl transition-[transform,box-shadow,background-color] duration-500 [transform-style:preserve-3d] hover:bg-[#FEFEFE]/95 hover:shadow-[9px_12px_0_rgba(87,149,21,0.12),0_26px_40px_-22px_rgba(87,149,21,0.5)] ${index % 2 === 0 ? "hover:[transform:translateY(-7px)_rotateX(5deg)_rotateY(-4deg)]" : "hover:[transform:translateY(-7px)_rotateX(5deg)_rotateY(4deg)] lg:translate-y-3"}`}
              >
                <span className="absolute right-4 top-3 display text-5xl font-bold text-[#ECECEC]">
                  0{index + 1}
                </span>
                <div
                  className="grid h-16 w-16 place-items-center rounded-full p-[5px] shadow-[0_7px_0_rgba(87,149,21,0.12)] transition-transform duration-700 [transform:translateZ(22px)] group-hover:rotate-[360deg]"
                  style={
                    {
                      background: `conic-gradient(${metric.color} ${metric.progress * 3.6}deg, #ECECEC 0deg)`,
                    } as CSSProperties
                  }
                >
                  <div className="grid h-full w-full place-items-center rounded-full bg-[#FEFEFE]">
                    <span className="display text-lg font-bold text-[#579515]">
                      {metric.value}
                    </span>
                  </div>
                </div>
                <h2 className="mt-4 font-semibold text-[#579515]">{metric.label}</h2>
                <p className="mt-2 text-xs leading-relaxed text-[#579515]/75">
                  {metric.description}
                </p>
                <span
                  className="absolute inset-x-0 bottom-0 h-1 origin-left scale-x-0 transition-transform duration-500 group-hover:scale-x-100"
                  style={{ backgroundColor: metric.color }}
                />
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* Sustainability story */}
      <section className="section-y relative overflow-hidden">
        <div className="container-x grid items-center gap-9 lg:grid-cols-12 lg:gap-12">
          <div className="relative lg:col-span-6">
            <div className="absolute -left-12 -top-10 h-48 w-48 rounded-full bg-[#579515]/10 blur-2xl" />
            <div className="relative overflow-hidden rounded-[1.5rem] bg-[#F5F5F5] shadow-[12px_12px_0_rgba(87,149,21,0.12),0_26px_45px_-26px_rgba(87,149,21,0.55)] transition-transform duration-700 [transform:rotateY(3deg)_rotateX(2deg)] hover:[transform:rotateY(0deg)_rotateX(0deg)_scale(1.015)]">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/images/sustainability/recycling.jpeg"
                alt="Colourful textiles arranged around a recycling symbol"
                className="aspect-[4/3] w-full object-cover opacity-80"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-[#579515] via-[#579515]/10 to-transparent" />
              <div className="absolute inset-x-0 bottom-0 p-5 text-[#FEFEFE] sm:p-6">
                <div className="text-[10px] font-semibold uppercase tracking-widest-x text-[#FBAA00]">
                  Reduce · Reuse · Recycle
                </div>
                <p className="display mt-2 max-w-md text-sm font-semibold leading-6 sm:text-base sm:leading-7">
                  Better outcomes begin with better production choices.
                </p>
              </div>
            </div>
            <div className="absolute -bottom-5 -right-2 hidden w-36 rounded-[1.25rem_0.4rem_1.25rem_0.4rem] border-4 border-[#FEFEFE] bg-[#579515]/90 p-4 text-[#FEFEFE] shadow-warm backdrop-blur-md transition-transform duration-500 hover:-translate-y-2 hover:rotate-2 sm:block">
              <FaLeaf className="h-5 w-5" />
              <div className="display mt-2 text-2xl font-bold">100%</div>
              <div className="mt-1 text-[9px] font-semibold uppercase tracking-widest-x text-[#FEFEFE]/75">
                Source segregation
              </div>
            </div>
          </div>

          <div className="lg:col-span-6 lg:pl-4">
            <SectionTitle
              eyebrow="Our direction"
              title="Progress with purpose"
              description="Environmental, social and governance priorities are built into everyday decisions—from the energy we generate to the way each order is packed."
            />
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="group rounded-[0.5rem_1.5rem_0.5rem_1.5rem] border border-[#579515]/25 bg-[#FEFEFE]/50 p-4 shadow-[6px_7px_0_rgba(87,149,21,0.12)] backdrop-blur-lg transition duration-500 hover:-translate-y-2 hover:bg-[#FEFEFE]/75 hover:shadow-[9px_10px_0_rgba(87,149,21,0.16)]">
                <FaGlobeAsia className="h-5 w-5 text-[#579515]" />
                <h3 className="mt-3 font-semibold text-[#579515]">Visible targets</h3>
                <p className="mt-2 text-sm leading-relaxed text-[#579515]/75">
                  Clear measures for energy, carbon, materials and ethical compliance.
                </p>
              </div>
              <div className="group rounded-[1.5rem_0.5rem_1.5rem_0.5rem] border border-[#FBAA00]/25 bg-[#FEFEFE]/50 p-4 shadow-[6px_7px_0_rgba(251,170,0,0.12)] backdrop-blur-lg transition duration-500 hover:-translate-y-2 hover:bg-[#FEFEFE]/75 hover:shadow-[9px_10px_0_rgba(251,170,0,0.16)]">
                <FaCertificate className="h-5 w-5 text-[#FBAA00]" />
                <h3 className="mt-3 font-semibold text-[#579515]">Verified progress</h3>
                <p className="mt-2 text-sm leading-relaxed text-[#579515]/75">
                  Supporting records and social-compliance documents available to buyers.
                </p>
              </div>
            </div>
            <p className="mt-5 border-l-2 border-[#FBAA00] pl-5 text-sm italic leading-relaxed text-[#579515]/80">
              Sustainability is not a separate programme. It is a more thoughtful way
              to design, make, pack and move every textile collection.
            </p>
          </div>
        </div>
      </section>

      {/* Five pillars */}
      <section className="section-y relative overflow-hidden bg-[#F5F5F5]">
        <div className="absolute left-0 top-0 h-px w-full bg-gradient-to-r from-transparent via-gold/50 to-transparent" />
        <div className="absolute -left-28 top-36 h-72 w-72 rounded-full border border-[#579515]/10" />
        <div className="absolute -right-32 bottom-16 h-80 w-80 rounded-full border border-[#FBAA00]/10" />
        <div className="container-x relative">
          <SectionTitle
            eyebrow="Five pillars"
            title="How responsibility moves through our operation"
            description="Practical interventions across energy, water, waste, packaging and ethical manufacturing turn sustainability from a statement into a repeatable process."
            align="center"
          />

          <div className="mx-auto grid max-w-6xl gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">
            {pillars.map(({ Icon, number, title, image, summary, points }, index) => (
              <article
                key={title}
                className={`group relative min-h-[238px] overflow-hidden rounded-2xl border border-[#579515]/15 bg-[#FEFEFE]/80 p-4 shadow-[4px_5px_0_rgba(87,149,21,0.09),0_16px_28px_-24px_rgba(87,149,21,0.5)] backdrop-blur-xl transition-[transform,box-shadow,background-color] duration-500 [transform-style:preserve-3d] hover:-translate-y-1.5 hover:bg-[#FEFEFE] hover:shadow-[7px_8px_0_rgba(251,170,0,0.14),0_22px_32px_-22px_rgba(87,149,21,0.48)] ${index % 2 === 0 ? "xl:translate-y-2" : ""}`}
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={image}
                  alt=""
                  aria-hidden="true"
                  className="absolute inset-0 h-full w-full object-cover opacity-[0.08] transition duration-700 group-hover:scale-110 group-hover:opacity-20"
                />
                <div className="absolute right-3 top-2 display text-5xl font-bold leading-none text-[#579515]/[0.07] transition-colors group-hover:text-[#579515]/10">
                  {number}
                </div>
                <div className="relative">
                  <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#579515] text-[#FEFEFE] shadow-[0_5px_0_rgba(87,149,21,0.28)] transition-transform duration-500 [transform:translateZ(20px)] group-hover:-rotate-6 group-hover:scale-105">
                    <Icon className="h-4 w-4" />
                  </div>
                  <div className="mt-4 text-[10px] font-semibold uppercase tracking-widest-x text-[#FBAA00]">
                    Pillar {number}
                  </div>
                  <h3 className="display mt-1 text-base font-semibold text-[#579515]">
                    {title}
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-[#579515]/80">
                    {summary}
                  </p>
                  <ul className="mt-3 grid gap-1.5 border-t border-[#ECECEC] pt-3">
                    {points.map((point) => (
                      <li key={point} className="flex items-start gap-2 text-xs leading-relaxed text-[#579515]/75">
                        <FaCheckCircle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#579515]" />
                        {point}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="absolute inset-x-0 bottom-0 h-1 origin-left scale-x-0 bg-[#579515] transition-transform duration-500 group-hover:scale-x-100" />
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* Water recovery */}
      <section className="relative overflow-hidden bg-[#F5F5F5] text-[#579515]">
        <div className="absolute inset-0 bg-weave-light opacity-40" />
        <div className="absolute -right-20 -top-24 h-96 w-96 rounded-full border-[70px] border-[#FBAA00]/[0.04]" />
        <div className="container-x relative py-12 md:py-16">
          <div className="grid gap-9 lg:grid-cols-12 lg:items-center">
            <div className="lg:col-span-4">
              <div className="flex items-center gap-3 text-[10px] font-semibold uppercase tracking-widest-x text-[#FBAA00]">
                <span className="h-px w-10 bg-[#FBAA00]" /> Water stewardship
              </div>
              <h2 className="display mt-5 text-3xl font-semibold leading-[1.1] sm:text-4xl">
                Recover.<br />Treat. Reuse.
              </h2>
              <p className="mt-4 max-w-md text-sm leading-relaxed text-[#579515]/80">
                Lower-consumption processing and recovery technology work together
                to reduce freshwater withdrawal.
              </p>
              <div className="mt-6 flex items-end gap-3">
                <span className="display text-6xl font-bold leading-none text-[#FBAA00] sm:text-7xl">
                  90
                </span>
                <div className="pb-2">
                  <div className="display text-2xl font-bold text-[#FBAA00]">%</div>
                  <div className="text-[9px] font-semibold uppercase tracking-widest-x text-[#579515]/70">
                    Process water recycled
                  </div>
                </div>
              </div>
            </div>

            <div className="lg:col-span-8">
              <div className="grid grid-cols-2 gap-3 [perspective:1100px] xl:grid-cols-4">
                {waterFlow.map(({ Icon, label, detail }, index) => (
                  <div
                    key={label}
                    className={`group relative flex min-h-[128px] flex-col items-center justify-center overflow-hidden rounded-2xl border border-[#579515]/15 bg-[#FEFEFE]/75 p-3 text-center shadow-[0_5px_0_rgba(87,149,21,0.09),0_14px_24px_-20px_rgba(87,149,21,0.45)] backdrop-blur-xl transition-[transform,background-color,box-shadow] duration-500 hover:bg-[#FEFEFE] hover:shadow-[0_8px_0_rgba(251,170,0,0.13),0_20px_28px_-18px_rgba(87,149,21,0.5)] ${index % 2 === 0 ? "hover:[transform:translateY(-5px)_rotateX(5deg)]" : "hover:[transform:translateY(-5px)_rotateX(-5deg)]"}`}
                  >
                    <span className="display absolute right-3 top-2 text-2xl font-bold text-[#579515]/10">
                      0{index + 1}
                    </span>
                    <div className="grid h-9 w-9 place-items-center rounded-full border border-[#FBAA00]/30 bg-[#FBAA00]/10 text-[#FBAA00] shadow-[0_4px_0_rgba(251,170,0,0.14)] transition group-hover:rotate-12 group-hover:bg-[#FBAA00] group-hover:text-[#579515]">
                      <Icon className="h-4 w-4" />
                    </div>
                    <h3 className="display mt-3 text-base font-bold">{label}</h3>
                    <p className="mt-1 text-xs text-[#579515]/75">{detail}</p>
                  </div>
                ))}
              </div>
              <div className="mt-4 flex items-center gap-3 text-xs text-[#579515]/70">
                <FaWater className="h-3.5 w-3.5 text-[#FBAA00]" />
                Process-water recycling reported in the company sustainability profile.
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Circularity */}
      <section className="section-y relative overflow-hidden bg-gradient-to-br from-[#F5F5F5] via-[#579515]/10 to-[#FBAA00]/10">
        <div className="absolute inset-0 bg-weave-light opacity-35" />
        <div className="absolute left-1/2 top-1/2 h-[520px] w-[520px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-dashed border-[#579515]/10" />
        <div className="container-x">
          <div className="relative grid items-center gap-8 lg:grid-cols-12 lg:gap-10">
            <div className="lg:col-span-4">
              <SectionTitle
                eyebrow="Circular thinking"
                title="Waste is a design problem"
                description="We work to reduce waste before it is created, separate unavoidable by-products and keep useful materials moving through the value chain."
              />
              <p className="text-sm leading-relaxed text-[#579515]/75">
                Our long-term direction is zero waste to landfill. It is stated as
                a goal—not a completed milestone—and is supported by source
                segregation and fabric-scrap upcycling.
              </p>
              <div className="mt-5 inline-flex items-center gap-3 rounded-full bg-[#FEFEFE] px-4 py-2.5 text-xs font-semibold text-[#579515] shadow-soft">
                <FaRecycle className="h-4 w-4" /> Closing the production loop
              </div>
            </div>

            <div className="lg:col-span-8">
              <div className="grid grid-cols-2 gap-4 [perspective:1000px] sm:grid-cols-3">
                {circularSteps.map(({ Icon, label }, index) => (
                  <div
                    key={label}
                    className={`group relative grid min-h-[125px] place-items-center bg-[#FEFEFE]/70 p-4 text-center shadow-[6px_7px_0_rgba(87,149,21,0.12)] backdrop-blur-xl transition-[transform,background-color,box-shadow] duration-500 [clip-path:polygon(25%_4%,75%_4%,100%_50%,75%_96%,25%_96%,0_50%)] hover:bg-[#FEFEFE]/95 hover:shadow-[9px_10px_0_rgba(251,170,0,0.15)] ${index % 2 === 0 ? "hover:[transform:translateY(-6px)_rotateZ(2deg)]" : "hover:[transform:translateY(-6px)_rotateZ(-2deg)]"}`}
                  >
                    <div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#579515]/10 text-[#579515] transition group-hover:bg-[#579515] group-hover:text-[#FEFEFE]">
                      <Icon className="h-4 w-4" />
                    </div>
                    <div className="mt-3 text-xs font-semibold text-[#579515]">
                      {label}
                    </div>
                    <span className="absolute right-3 top-3 display text-sm font-bold text-[#FBAA00]/60">
                      0{index + 1}
                    </span>
                    {index < circularSteps.length - 1 && index !== 2 && (
                      <FaArrowRight className="absolute -right-2.5 top-1/2 z-10 hidden h-3 w-3 -translate-y-1/2 text-[#579515]/40 sm:block" />
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Closing CTA */}
      <section className="section-y overflow-hidden bg-[#FEFEFE]">
        <div className="container-x">
          <div className="group relative overflow-hidden rounded-[2rem_0.75rem_2rem_0.75rem] border border-[#579515]/15 bg-[#FEFEFE]/70 px-6 py-9 text-[#579515] shadow-[10px_12px_0_rgba(87,149,21,0.1),0_26px_48px_-30px_rgba(87,149,21,0.5)] backdrop-blur-xl transition duration-700 hover:bg-[#FEFEFE]/90 hover:shadow-[14px_16px_0_rgba(87,149,21,0.13),0_34px_55px_-28px_rgba(87,149,21,0.55)] sm:px-9 lg:px-12 lg:py-11">
            <div className="absolute inset-0 bg-weave-light opacity-60" />
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/images/sustainability/solar.jpeg"
              alt=""
              aria-hidden="true"
              className="absolute inset-y-0 right-0 h-full w-1/2 object-cover opacity-10"
            />
            <div className="absolute inset-0 bg-gradient-to-r from-[#F5F5F5] via-[#F5F5F5]/95 to-[#F5F5F5]/70" />
            <FaLeaf className="absolute -bottom-8 -right-4 h-52 w-52 rotate-[-15deg] text-[#FBAA00]/[0.1]" />
            <div className="relative grid items-center gap-8 lg:grid-cols-12">
              <div className="lg:col-span-8">
                <div className="flex items-center gap-3 text-[10px] font-semibold uppercase tracking-widest-x text-[#FBAA00]">
                  <FaCertificate className="h-4 w-4" /> Responsible partnerships
                </div>
                <h2 className="display mt-4 text-3xl font-semibold leading-[1.1] sm:text-4xl">
                  Building a more transparent textile supply chain.
                </h2>
                <p className="mt-4 max-w-2xl leading-relaxed text-[#579515]/80">
                  Speak with our team about material choices, buyer requirements,
                  social-compliance documentation and sustainability targets for
                  your next collection.
                </p>
              </div>
              <div className="flex flex-wrap gap-3 lg:col-span-4 lg:flex-col lg:items-stretch">
                <Link href="/contact" className="btn-gold">
                  Start a conversation <FaArrowRight className="h-3 w-3" />
                </Link>
                <Link
                  href="/certifications"
                  className="btn-outline"
                >
                  View certifications
                </Link>
              </div>
            </div>
          </div>

          <p className="mt-4 text-center text-[11px] leading-relaxed text-[#579515]/70">
            Sustainability figures and statements are based on the company profile
            supplied by {siteConfig.name}. “Zero waste to landfill” is an ongoing goal.
          </p>
        </div>
      </section>
    </main>
  );
}
