import type { CSSProperties } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import {
  FaArrowRight,
  FaBoxOpen,
  FaCertificate,
  FaCheckCircle,
  FaGlobeAsia,
  FaHandHoldingWater,
  FaIndustry,
  FaLeaf,
  FaRecycle,
  FaSeedling,
  FaShippingFast,
  FaSolarPanel,
  FaUsers,
  FaWater,
} from "react-icons/fa";

import PageHero from "@/components/PageHero";
import SectionTitle from "@/components/SectionTitle";
import { siteConfig } from "@/data/site";

export const metadata: Metadata = {
  title: "Sustainability",
  description: `See how ${siteConfig.name} approaches renewable energy, water recovery, waste reduction, responsible packaging and ethical manufacturing.`,
};

const metrics = [
  {
    value: "50%",
    progress: 50,
    label: "Renewable electricity",
    description: "of total electricity usage is generated by on-site rooftop solar panels.",
    color: "#d89b12",
  },
  {
    value: "−15%",
    progress: 15,
    label: "Carbon emissions",
    description: "year-over-year reduction in Scope 1 & 2 CO₂ emissions per unit produced.",
    color: "#4b5563",
  },
  {
    value: "85%",
    progress: 85,
    label: "Certified eco materials",
    description: "supported by FSC-certified cartons and sustainable poly bags.",
    color: "#718b34",
  },
  {
    value: "100%",
    progress: 100,
    label: "Audited facilities",
    description: "facilities maintaining amfori BSCI social-compliance auditing.",
    color: "#b85b24",
  },
];

const pillars = [
  {
    Icon: FaSolarPanel,
    number: "01",
    title: "Solar energy",
    image: "/images/sustainability/solar.jpeg",
    summary:
      "Rooftop solar generation helps reduce dependence on conventional grid electricity across our operations.",
    points: ["50% renewable electricity", "On-site rooftop generation", "Lower operational emissions"],
  },
  {
    Icon: FaWater,
    number: "02",
    title: "Water management",
    image: "/images/sustainability/water.jpeg",
    summary:
      "Engineering-led process controls minimise freshwater withdrawal and maximise recovery for reuse.",
    points: ["Low-liquor ratio dyeing & printing", "90% process-water recycling", "Reverse-osmosis recovery"],
  },
  {
    Icon: FaRecycle,
    number: "03",
    title: "Waste & recycling",
    image: "/images/sustainability/recycling.jpeg",
    summary:
      "Production by-products are separated at source and redirected towards useful second-life applications.",
    points: ["100% source segregation", "Fabric-scrap upcycling", "Zero waste to landfill goal"],
  },
  {
    Icon: FaBoxOpen,
    number: "04",
    title: "Eco-conscious packaging",
    image: "/images/sustainability/packaging.jpeg",
    summary:
      "Packaging is designed to reduce single-use plastic and material waste while protecting every shipment.",
    points: ["FSC-certified cartons", "Sustainable poly bags", "Freight optimisation"],
  },
  {
    Icon: FaUsers,
    number: "05",
    title: "Ethical manufacturing",
    image: "/images/sustainability/solar.jpeg",
    summary:
      "Responsible workplace practices support the people behind every product and strengthen accountability across our operation.",
    points: ["Audited facilities", "Fair workplace practices", "Responsible sourcing"],
  },
];

const waterFlow = [
  { Icon: FaHandHoldingWater, label: "Lower intake", detail: "Freshwater demand minimised" },
  { Icon: FaIndustry, label: "Efficient process", detail: "Low-liquor production" },
  { Icon: FaRecycle, label: "90% recycled", detail: "Process water recovered" },
  { Icon: FaWater, label: "RO recovery", detail: "Water prepared for reuse" },
];

const circularSteps = [
  { Icon: FaSeedling, label: "Responsible inputs" },
  { Icon: FaIndustry, label: "Efficient production" },
  { Icon: FaRecycle, label: "Source segregation" },
  { Icon: FaLeaf, label: "Scrap upcycling" },
  { Icon: FaBoxOpen, label: "Smarter packaging" },
  { Icon: FaShippingFast, label: "Optimised freight" },
];

export default function SustainabilityPage() {
  return (
    <>
      <PageHero
        eyebrow="Responsibility in every thread"
        title="Textiles made with tomorrow in mind."
        subtitle="From solar-powered operations and water recovery to responsible materials and ethical labour, we are working towards a lighter footprint."
        bgImage="/images/sustainability/solar.jpeg"
        breadcrumbs={[
          { label: "Home", href: "/" },
          { label: "Sustainability" },
        ]}
      />

      {/* Impact dashboard */}
      <section className="relative z-10 -mt-10 pb-16 md:-mt-14 md:pb-24">
        <div className="container-x">
          <div className="grid overflow-hidden rounded-3xl border border-cream-200 bg-white shadow-warm sm:grid-cols-2 lg:grid-cols-4">
            {metrics.map((metric, index) => (
              <article
                key={metric.label}
                className="group relative min-h-[220px] overflow-hidden border-b border-cream-200 p-6 last:border-b-0 sm:[&:nth-child(3)]:border-b-0 sm:[&:nth-child(4)]:border-b-0 lg:border-b-0 lg:border-r lg:last:border-r-0 lg:p-7"
              >
                <span className="absolute right-4 top-3 display text-5xl font-bold text-cream-200/70">
                  0{index + 1}
                </span>
                <div
                  className="grid h-20 w-20 place-items-center rounded-full p-[6px] transition-transform duration-500 group-hover:rotate-12"
                  style={
                    {
                      background: `conic-gradient(${metric.color} ${metric.progress * 3.6}deg, #f3ead4 0deg)`,
                    } as CSSProperties
                  }
                >
                  <div className="grid h-full w-full place-items-center rounded-full bg-white">
                    <span className="display text-xl font-bold text-gray-950">
                      {metric.value}
                    </span>
                  </div>
                </div>
                <h2 className="mt-5 font-semibold text-gray-950">{metric.label}</h2>
                <p className="mt-2 text-xs leading-relaxed text-ink-muted">
                  {metric.description}
                </p>
                <span
                  className="absolute inset-x-0 bottom-0 h-1 origin-left scale-x-0 transition-transform duration-500 group-hover:scale-x-100"
                  style={{ backgroundColor: metric.color }}
                />
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* Sustainability story */}
      <section className="overflow-hidden pb-16 md:pb-24">
        <div className="container-x grid items-center gap-12 lg:grid-cols-12 lg:gap-16">
          <div className="relative lg:col-span-6">
            <div className="absolute -left-12 -top-10 h-48 w-48 rounded-full bg-[#718b34]/10 blur-2xl" />
            <div className="relative overflow-hidden rounded-[2rem] bg-gray-950 shadow-warm">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/images/sustainability/recycling.jpeg"
                alt="Colourful textiles arranged around a recycling symbol"
                className="aspect-[4/3] w-full object-cover opacity-80"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-gray-950 via-gray-950/10 to-transparent" />
              <div className="absolute inset-x-0 bottom-0 p-7 text-cream-50 sm:p-9">
                <div className="text-[10px] font-semibold uppercase tracking-widest-x text-gold-light">
                  Reduce · Reuse · Recycle
                </div>
                <p className="display mt-2 max-w-md text-2xl font-bold leading-snug sm:text-3xl">
                  Better outcomes begin with better production choices.
                </p>
              </div>
            </div>
            <div className="absolute -bottom-8 -right-3 hidden w-44 rounded-2xl border-4 border-cream-50 bg-[#718b34] p-5 text-white shadow-warm sm:block">
              <FaLeaf className="h-5 w-5" />
              <div className="display mt-3 text-3xl font-bold">100%</div>
              <div className="mt-1 text-[9px] font-semibold uppercase tracking-widest-x text-white/75">
                Source segregation
              </div>
            </div>
          </div>

          <div className="lg:col-span-6 lg:pl-4">
            <SectionTitle
              eyebrow="Our direction"
              title="Progress with purpose"
              description="Environmental, social and governance priorities are built into everyday decisions—from the energy we generate to the way each order is packed."
            />
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="rounded-2xl border border-[#718b34]/20 bg-[#718b34]/[0.07] p-5">
                <FaGlobeAsia className="h-5 w-5 text-[#60772f]" />
                <h3 className="mt-4 font-semibold text-gray-950">Visible targets</h3>
                <p className="mt-2 text-sm leading-relaxed text-ink-muted">
                  Clear measures for energy, carbon, materials and ethical compliance.
                </p>
              </div>
              <div className="rounded-2xl border border-gold/20 bg-gold/[0.06] p-5">
                <FaCertificate className="h-5 w-5 text-gold-dark" />
                <h3 className="mt-4 font-semibold text-gray-950">Verified progress</h3>
                <p className="mt-2 text-sm leading-relaxed text-ink-muted">
                  Supporting records and social-compliance documents available to buyers.
                </p>
              </div>
            </div>
            <p className="mt-6 border-l-2 border-gold pl-5 text-sm italic leading-relaxed text-ink-soft">
              Sustainability is not a separate programme. It is a more thoughtful way
              to design, make, pack and move every textile collection.
            </p>
          </div>
        </div>
      </section>

      {/* Five pillars */}
      <section className="section-y relative overflow-hidden bg-cream-100/70">
        <div className="absolute left-0 top-0 h-px w-full bg-gradient-to-r from-transparent via-gold/50 to-transparent" />
        <div className="absolute -left-28 top-36 h-72 w-72 rounded-full border border-[#718b34]/10" />
        <div className="absolute -right-32 bottom-16 h-80 w-80 rounded-full border border-gold/10" />
        <div className="container-x relative">
          <SectionTitle
            eyebrow="Five pillars"
            title="How responsibility moves through our operation"
            description="Practical interventions across energy, water, waste, packaging and ethical manufacturing turn sustainability from a statement into a repeatable process."
            align="center"
          />

          <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-6">
            {pillars.map(({ Icon, number, title, image, summary, points }, index) => (
              <article
                key={title}
                className={`group relative min-h-[350px] overflow-hidden rounded-[2rem] border border-white/80 bg-white p-7 shadow-soft transition duration-500 hover:-translate-y-1.5 hover:shadow-warm sm:p-9 xl:col-span-2 ${
                  index === 3 ? "xl:col-start-2" : ""
                }`}
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={image}
                  alt=""
                  aria-hidden="true"
                  className="absolute inset-0 h-full w-full object-cover opacity-10 transition duration-700 group-hover:scale-105 group-hover:opacity-20"
                />
                <div className="absolute right-5 top-2 display text-[6rem] font-bold leading-none text-[#718b34]/[0.07] transition-colors group-hover:text-[#718b34]/10 sm:text-[7rem]">
                  {number}
                </div>
                <div className="relative">
                  <div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#718b34] text-white shadow-lg shadow-[#718b34]/20 transition-transform duration-500 group-hover:-rotate-6 group-hover:scale-110">
                    <Icon className="h-5 w-5" />
                  </div>
                  <div className="mt-6 text-[10px] font-semibold uppercase tracking-widest-x text-gold-dark">
                    Pillar {number}
                  </div>
                  <h3 className="display mt-2 text-3xl font-bold text-gray-950">
                    {title}
                  </h3>
                  <p className="mt-4 max-w-xl leading-relaxed text-ink-soft">
                    {summary}
                  </p>
                  <ul className="mt-7 grid gap-3 border-t border-cream-200/80 pt-6 sm:grid-cols-3">
                    {points.map((point) => (
                      <li key={point} className="flex items-start gap-2 text-xs leading-relaxed text-ink-muted">
                        <FaCheckCircle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#718b34]" />
                        {point}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="absolute inset-x-0 bottom-0 h-1 origin-left scale-x-0 bg-[#718b34] transition-transform duration-500 group-hover:scale-x-100" />
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* Water recovery */}
      <section className="relative overflow-hidden bg-gray-950 text-cream-50">
        <div className="absolute inset-0 bg-weave-dark opacity-40" />
        <div className="absolute -right-20 -top-24 h-96 w-96 rounded-full border-[70px] border-white/[0.025]" />
        <div className="container-x relative py-16 md:py-24">
          <div className="grid gap-12 lg:grid-cols-12 lg:items-center">
            <div className="lg:col-span-4">
              <div className="flex items-center gap-3 text-[10px] font-semibold uppercase tracking-widest-x text-gold-light">
                <span className="h-px w-10 bg-gold" /> Water stewardship
              </div>
              <h2 className="display mt-5 text-4xl font-bold leading-tight sm:text-5xl">
                Recover.<br />Treat. Reuse.
              </h2>
              <p className="mt-5 max-w-md text-sm leading-relaxed text-cream-100/70">
                Lower-consumption processing and recovery technology work together
                to reduce freshwater withdrawal.
              </p>
              <div className="mt-8 flex items-end gap-3">
                <span className="display text-7xl font-bold leading-none text-gold-light sm:text-8xl">
                  90
                </span>
                <div className="pb-2">
                  <div className="display text-3xl font-bold text-gold-light">%</div>
                  <div className="text-[9px] font-semibold uppercase tracking-widest-x text-cream-100/60">
                    Process water recycled
                  </div>
                </div>
              </div>
            </div>

            <div className="lg:col-span-8">
              <div className="grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2">
                {waterFlow.map(({ Icon, label, detail }, index) => (
                  <div
                    key={label}
                    className="group relative bg-gray-950/85 p-7 transition hover:bg-gray-900 sm:p-8"
                  >
                    <span className="absolute right-5 top-4 display text-4xl font-bold text-white/[0.06]">
                      0{index + 1}
                    </span>
                    <div className="grid h-12 w-12 place-items-center rounded-full border border-gold/30 bg-gold/10 text-gold-light transition group-hover:bg-gold group-hover:text-gray-950">
                      <Icon className="h-4 w-4" />
                    </div>
                    <h3 className="display mt-5 text-xl font-bold">{label}</h3>
                    <p className="mt-2 text-xs text-cream-100/60">{detail}</p>
                  </div>
                ))}
              </div>
              <div className="mt-5 flex items-center gap-3 text-xs text-cream-100/50">
                <FaWater className="h-3.5 w-3.5 text-gold-light" />
                Process-water recycling reported in the company sustainability profile.
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Circularity */}
      <section className="section-y relative overflow-hidden bg-[#718b34]/[0.07]">
        <div className="absolute left-1/2 top-1/2 h-[520px] w-[520px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-dashed border-[#718b34]/10" />
        <div className="container-x">
          <div className="relative grid items-center gap-12 lg:grid-cols-12 lg:gap-16">
            <div className="lg:col-span-4">
              <SectionTitle
                eyebrow="Circular thinking"
                title="Waste is a design problem"
                description="We work to reduce waste before it is created, separate unavoidable by-products and keep useful materials moving through the value chain."
              />
              <p className="text-sm leading-relaxed text-ink-muted">
                Our long-term direction is zero waste to landfill. It is stated as
                a goal—not a completed milestone—and is supported by source
                segregation and fabric-scrap upcycling.
              </p>
              <div className="mt-7 inline-flex items-center gap-3 rounded-full bg-white px-5 py-3 text-xs font-semibold text-[#526828] shadow-soft">
                <FaRecycle className="h-4 w-4" /> Closing the production loop
              </div>
            </div>

            <div className="lg:col-span-8">
              <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
                {circularSteps.map(({ Icon, label }, index) => (
                  <div
                    key={label}
                    className="group relative min-h-[145px] rounded-2xl border border-white bg-white/90 p-5 text-center shadow-soft transition duration-300 hover:-translate-y-1 hover:bg-white hover:shadow-warm"
                  >
                    <div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#718b34]/10 text-[#526828] transition group-hover:bg-[#718b34] group-hover:text-white">
                      <Icon className="h-4 w-4" />
                    </div>
                    <div className="mt-4 text-xs font-semibold text-gray-950">
                      {label}
                    </div>
                    <span className="absolute right-3 top-3 display text-sm font-bold text-gold/60">
                      0{index + 1}
                    </span>
                    {index < circularSteps.length - 1 && index !== 2 && (
                      <FaArrowRight className="absolute -right-2.5 top-1/2 z-10 hidden h-3 w-3 -translate-y-1/2 text-[#718b34]/40 sm:block" />
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Closing CTA */}
      <section className="section-y overflow-hidden">
        <div className="container-x">
          <div className="relative overflow-hidden rounded-[2rem] bg-gray-950 px-7 py-12 text-cream-50 shadow-warm sm:px-12 lg:px-16 lg:py-16">
            <div className="absolute inset-0 bg-weave-dark opacity-60" />
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/images/sustainability/solar.jpeg"
              alt=""
              aria-hidden="true"
              className="absolute inset-y-0 right-0 h-full w-1/2 object-cover opacity-10"
            />
            <div className="absolute inset-0 bg-gradient-to-r from-gray-950 via-gray-950/95 to-gray-950/55" />
            <FaLeaf className="absolute -bottom-8 -right-4 h-52 w-52 rotate-[-15deg] text-gold/[0.1]" />
            <div className="relative grid items-center gap-8 lg:grid-cols-12">
              <div className="lg:col-span-8">
                <div className="flex items-center gap-3 text-[10px] font-semibold uppercase tracking-widest-x text-gold-light">
                  <FaCertificate className="h-4 w-4" /> Responsible partnerships
                </div>
                <h2 className="display mt-4 text-4xl font-bold leading-tight md:text-5xl">
                  Building a more transparent textile supply chain.
                </h2>
                <p className="mt-5 max-w-2xl leading-relaxed text-cream-100/75">
                  Speak with our team about material choices, buyer requirements,
                  social-compliance documentation and sustainability targets for
                  your next collection.
                </p>
              </div>
              <div className="flex flex-wrap gap-3 lg:col-span-4 lg:flex-col lg:items-stretch">
                <Link href="/contact" className="btn-gold">
                  Start a conversation <FaArrowRight className="h-3 w-3" />
                </Link>
                <Link
                  href="/certifications"
                  className="btn border border-cream-50/25 text-cream-50 hover:border-gold hover:text-gold-light"
                >
                  View certifications
                </Link>
              </div>
            </div>
          </div>

          <p className="mt-5 text-center text-[11px] leading-relaxed text-ink-muted">
            Sustainability figures and statements are based on the company profile
            supplied by {siteConfig.name}. “Zero waste to landfill” is an ongoing goal.
          </p>
        </div>
      </section>
    </>
  );
}
